cumulus/starcluster/tasks/cluster.py, tests/CMakeLists.txt, tests/cases/cluster_test.py, tests/cases/fixtures/config
In particular handle errors caused by trying to create clusters
bigger than the 'max-instance' limit. Fixes #1
=> Add error handling for ClusterValidationError

config.json, girder/task/server/models/task.py, girder/task/server/task.py, tests/cumulus_mock_plugin/plugin.json, tests/cumulus_mock_plugin/server/__init__.py, tests/cumulus_mock_plugin/server/cluster.py, tests/task_mock_plugin/plugin.json, tests/task_mock_plugin/server/__init__.py, tests/task_mock_plugin/server/task.py
This is to enable UI development and testing
=> Add to mock plugins to allow task to run without AWS

cumulus/__init__.py, cumulus/common.py, cumulus/constants.py, cumulus/starcluster/tasks/cluster.py, cumulus/starcluster/tasks/common.py, girder/cumulus/plugin.cmake, girder/cumulus/plugin_tests/cluster_test.py, girder/cumulus/plugin_tests/starclusterconfig_test.py, girder/cumulus/plugin_tests/volume_test.py, girder/cumulus/server/__init__.py, girder/cumulus/server/cluster.py, girder/cumulus/server/job.py, girder/cumulus/server/models/volume.py, girder/cumulus/server/script.py, girder/cumulus/server/starclusterconfig.py, girder/cumulus/server/utility/volume_adapters.py, girder/cumulus/server/volume.py, girder/pvwproxy/server/proxy.py, girder/task/server/task.py, tests/cases/job_test.py
Endpoint to allow the creation, attachment and detachment of ESB volumes.
=> Add volume endpoint

girder/cumulus/server/aws.py, girder/cumulus/server/cluster.py, girder/cumulus/server/job.py
=> Document status endpoints

tasks/pvw.json, tasks/pvw_trad.json
=> Fixes json spec errors

girder/register/plugin.json, girder/register/server/__init__.py
This is temporary until we have a better admin interface
=> Add plugin to add new users to correct group

scripts/dummy.sh, tasks/hydra_trad.json
For dummy task leave mesh to use with visualizer
=> Leave mesh in job directory

.travis.yml, cumulus/common/girder.py, girder/cumulus/plugin_tests/cluster_test.py, girder/cumulus/server/models/cluster.py, girder/cumulus/server/utility/cluster_adapters.py
If a cluster has an assetstore associated with it remove it when the cluster is deleted.
=> Clean up cluster assetstores

cumulus/templates/schedulers/pbs.sh, cumulus/templates/schedulers/sge.sh, cumulus/templates/schedulers/slurm.sh
=> Allow an accounting string to be provided

cumulus/aws/ec2/tasks/key.py, cumulus/celery/__init__.py, cumulus/celery/commandconfig.py, cumulus/mytaskflows.py, cumulus/ssh/tasks/key.py, cumulus/starcluster/tasks/cluster.py, cumulus/starcluster/tasks/job.py, cumulus/task/runner.py, cumulus/task/status.py, cumulus/taskflow.py
Note:  This will require changes to /etc/default/celeryd - in particular
the values:
```
CELERYD_NODES = "cumulus"
....
CELERYD_OPTS=""
....
```
This change will have to be made in HPCCloud-deploy once these changes
make thier way into master. ([here](https://github.com/Kitware/HPCCloud-deploy/blob/master/ansible/roles/celery/files/celeryd#L7) & [here](https://github.com/Kitware/HPCCloud-deploy/blob/master/ansible/roles/celery/files/celeryd#L22))
=> Refactor celery app to include taskflow queue

cumulus/celery/__init__.py
=> Remove non-existent task from _includes

cumulus/celery/__init__.py, cumulus/queue/abstract.py, cumulus/queue/pbs.py, cumulus/queue/sge.py, cumulus/queue/slurm.py, cumulus/starcluster/tasks/job.py, cumulus/taskflow/__init__.py, girder/cumulus/server/job.py, tests/cases/job_test.py, tests/cases/pbs_test.py, tests/cases/sge_test.py, tests/cases/slurm_test.py
Allow multiple jobs to be monitored with a single task.
=> Refactor monitor_job to accept multiple jobs

cumulus/ansible/tasks/cluster.py, cumulus/ansible/tasks/inventory.py, cumulus/ansible/tasks/playbooks/callback_plugins/cumulus_log.py, cumulus/ansible/tasks/playbooks/default.yml, tests/cases/ansible_test.py
refactor ansible running portion of the code to be compliant with GPL
=> GPL refactor

cumulus/ansible/tasks/playbooks/callback_plugins/cumulus_log.py, cumulus/ansible/tasks/playbooks/roles/ec2-pod/tasks/main.yml, requirements.txt, tests/cases/ansible_run_log_test.py, tests/cases/fixtures/ansible/test_run_playbook.yml
Fixes ```cumulus_log.py``` and ```ec2-pod``` role to work with ansible 2.0
***breaks backwards compatability with ansible 1.9.X***
=> Require ansible 2.0

requirements.txt
@cjh1 PTAL when you get a chance
=> Girder client required by taskflow, other modules

cumulus/aws/ec2/tasks/key.py
This reverts commit d78a872883d13b1089610cb39d54be0025df52e0.
=> Revert "Make keys group readable"

cumulus/tasks/cluster.py
=> Change test command to pwd

requirements.txt
We need some fixes that are not currently in a release
=> Bump girder_client to master

girder/cumulus/plugin_tests/cluster_test.py, girder/cumulus/server/utility/cluster_adapters.py
To ensure IntEnum's are converted to strings
=> Filter cluster after update

girder/cumulus/plugin_tests/ansible_test.py, girder/cumulus/plugin_tests/cluster_test.py, girder/cumulus/server/models/cluster.py, girder/cumulus/server/utility/cluster_adapters.py
Makes sure cluster 'access' settings are not effected by changing
cluster status. @cjh1 PTAL
=> Fix issues with /cluster/%s/log returning 500

cumulus/common/girder.py, girder/cumulus/server/cluster.py, girder/cumulus/server/job.py, girder/cumulus/server/utility/cluster_adapters.py
=> Move cluster filter to edges of girder's interface

cumulus/constants.py
=> added terminating to cluster status transition list of error

cumulus/ansible/tasks/providers/ec2.py, girder/cumulus/plugin_tests/volume_test.py, girder/cumulus/server/volume.py
Fix attach volume test
Fix create volume tests
Fix delete volume test
Fix detach volume test
Fix find volume test
Fix get status volume test
Fix get volume test
Remove skips, fix static analysis
=> Fix volume REST test

girder/cumulus/server/volume.py
=> Allow for deleting newly created volumes

girder/cumulus/server/cluster.py, girder/cumulus/server/job.py
@TristanWright These are the cumulus related swagger changes needed.
=> Update URIs for $ref properties

.travis.yml
Turn off new Girder option JAVASCRIPT_STYLE_TESTS
=> Switch off JAVASCRIPT_STYLE_TESTS

cumulus/ansible/tasks/inventory.py, cumulus/ansible/tasks/playbooks/callback_plugins/cumulus_log.py, cumulus/ansible/tasks/playbooks/library/girder.py, cumulus/ansible/tasks/providers/ec2.py, cumulus/scripts/command.py, cumulus/scripts/utils.py, cumulus/ssh/tasks/key.py, girder/cumulus/server/aws.py, girder/cumulus/server/cluster.py, requirements-dev.txt, tests/flake8.cfg, tests/integration/integration.py
We needed to upgrade flake8-quotes to be compatible with flake8 version the, this required use to clean up a little.
=> Flake8 quote fix

cumulus/celery/__init__.py, cumulus/celery/commonconfig.py
This makes it easier to configure at deploy time.
=> Move broker URI into separate file

girder/newt/server/assetstore.py
This allow files to be accessed from other plugins, not just HTTP requests.
=> Fix internal download of file held in NEWT assetstore

girder/newt/server/__init__.py, girder/newt/server/constants.py, girder/newt/server/rest.py
This allows NEWT users to login to an instance that is otherwise closed for registration.
=> Add NEWT plugin setting to ignore closed registration

.travis.yml, cumulus/girderclient.py, requirements-dev.txt, requirements.txt, tests/flake8.cfg
No longer uses multi-part requests.
CC @psavery
=> fix(girderclient): file/chunk endpoint changes for girder 3

girder/newt/newt/__init__.py
Girder3 removed the `users.login_regex` option, which was needed to support NERSC user logins that are less than 4 characters in length. This branch updates the NewtPlugin to replace the login validate code in the girder user model in order to support shorter login names. The new validate method is copied from the girder method and only changes the regex string to the one used previously for NERSC/NEWT authentication.
=> Add custom validation for NEWT logins

cumulus/transport/files/__init__.py
If multiple taskflows are running at the same time, and the cluster
doesn't yet have an associated assetstore, there is a possibility for
more than one task to try and create an assetstore with the same name,
causing an exception.
Fixes: https://github.com/OpenChemistry/openchemistrypy/issues/80
=> Fix assetstore creation when multiple tasks are running
